# Generated by Django 5.1.2 on 2024-10-20 18:11

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MultiLayeredPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('POLL', 'Poll'), ('QUIZ', 'Quiz'), ('CTA', 'Call to Action')], max_length=20)),
                ('main_content', models.TextField(blank=True, null=True)),
                ('interactive_layer', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollaborativePost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('collaboration_message', models.TextField(max_length=5000)),
                ('contributors', models.ManyToManyField(related_name='collaborative_posts', to=settings.AUTH_USER_MODEL)),
                ('main_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaborative_post', to='content.multilayeredpost')),
            ],
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='post_attachments/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.multilayeredpost')),
            ],
        ),
        migrations.CreateModel(
            name='TimeCapsulePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reveal_date', models.DateTimeField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_capsule', to='content.multilayeredpost')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='videos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
